name: CI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 8

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REG_USERNAME }}
          password: ${{ secrets.DOCKER_REG_PASSWORD }}

      - name: Build and Push Docker images
        id: docker_build
        uses: docker/build-push-action@v3
        env:
          APP_VERSION: ${{ github.ref_name }}-${{ steps.short-sha.outputs.sha }}
        with:
          context: ./
          push: true
          build-args: |
            APP_VERSION=${{ env.APP_VERSION }}
          tags: |
            aelitadoc/infercode-server:latest
            aelitadoc/infercode-server:${{ env.APP_VERSION }}
          # https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
